version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stackflow-api
    ports:
      - "8080:8080"
    networks:
      - backend-net

# volumes:
#   pgdata:

networks:
  backend-net:
